version: "3.7"

services:
  app:
    container_name: go-todos
    image: golang:1.14.15
    ports:
      - 3000:3000
    volumes: 
      - ./:/todos
    working_dir: /todos
    command: go run main.go
