basePath: /
definitions:
  orders.Order:
    properties:
      book:
        items:
          type: integer
        type: array
      description:
        type: string
      id:
        items:
          type: integer
        type: array
    type: object
  orders.OrderCreateDTO:
    properties:
      book:
        items:
          type: integer
        type: array
      description:
        type: string
    type: object
  orders.OrderID:
    properties:
      id:
        items:
          type: integer
        type: array
    type: object
host: localhost:8002
info:
  contact:
    email: dmitry@vesnin.work
    name: Dimas
    url: https://github.com/Vesninovich
  description: Service for placing and reading book orders
  license:
    name: ISC
    url: https://www.isc.org/licenses/
  title: Book Store Orders Service
  version: "0.0"
paths:
  /order:
    get:
      consumes:
      - application/json
      description: get order by id
      parameters:
      - description: order id
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/orders.OrderID'
      produces:
      - application/json
      responses:
        "200":
          description: requested order
          schema:
            $ref: '#/definitions/orders.Order'
        "400":
          description: malformed id
          schema:
            type: string
        "404":
          description: requested order not found
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: get order
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: place new book order
      parameters:
      - description: order data
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/orders.OrderCreateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: created order
          schema:
            $ref: '#/definitions/orders.Order'
        "400":
          description: malformed book id
          schema:
            type: string
        "404":
          description: requested book not found
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: place order
      tags:
      - Order
swagger: "2.0"
tags:
- description: Requesting and placing orders
  name: Order
